apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: order-saga-trigger
  annotations:
    eventing.knative.dev/injection: enabled
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.kafka.event
      source: /apis/v1/namespaces/camel-demo/kafkasources/kafka-source-reserve-order#reserve-events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-saga
    uri: /orders/confirm